[package]
name = "rtforth"
version = "0.1.0"
authors = ["Sirius Wu <ccwu660601@gmail.com>"]

[dependencies]
ws = "*"
bounded-spsc-queue = "*"

[dependencies.rtforth]
git = "https://github.com/chengchangwu/rtforth.git"
